# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [17]:
import numpy as np


In [21]:
dfile = np.loadtxt('minutes_n_ingredients.csv', delimiter = ',', dtype = 'int32', skiprows = 1)
dfile[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [22]:
dfile1 = dfile[:, 1:] #массив без 1го столбца
srednelement = np.average(dfile1, 0)
print('ср зн по столбцам:', srednelement)
maxelement = np.max(dfile1, 0)
print('макс знач по столбцам:', maxelement)
minelement = np.min(dfile1, 0)
print('мин знач по столбцам:', minelement)
medianelement = np.median(dfile1, 0)
print('медиана по столбцам:', medianelement)

ср зн по столбцам: [2.16010017e+04 9.05528000e+00]
макс знач по столбцам: [2147483647         39]
мин знач по столбцам: [0 1]
медиана по столбцам: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [25]:
q = np.quantile(dfile[:,1], 0.75, axis = 0) #вычисленный квантиль
dfile3 = dfile[dfile[:, 1] <= q]
print(dfile3.shape[0])
print('\n',dfile3)

75461

 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [29]:
dfile4 = dfile[dfile[:, 1] == 0]
print(dfile4.shape[0]) 
dfile44 = np.copy(dfile) 
np.place(dfile44[:, 1], dfile44[:, 1] == 0, 1) 
dfile[410:413], dfile44[410:413] 

479


(array([[ 18800,    270,     17],
        [  9325,      0,     10],
        [422167,     45,      8]]),
 array([[ 18800,    270,     17],
        [  9325,      1,     10],
        [422167,     45,      8]]))

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [31]:
len(np.unique(dfile[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [32]:
print(f'Количество различных значений ингредиентов: {len(np.unique(dfile[:,2]))}')
print(np.unique(dfile[:,2]))

Количество различных значений ингредиентов: 37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [33]:
print(dfile[dfile[:,2] <= 5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [36]:
dfile8 = dfile[:, 2] / dfile44[:, 1] 
print('Максимальное количество ингридиентов на одну минуту рецепта:',np.max(dfile8))
print(dfile8[:,np.newaxis]) 


Максимальное количество ингридиентов на одну минуту рецепта: 24.0
[[0.26666667]
 [0.28      ]
 [0.6       ]
 ...
 [0.23076923]
 [0.8       ]
 [0.1       ]]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [37]:
dfile9 = np.copy(dfile)
dfile9 = np.sort(dfile9, axis = 0)[::-1][:100]
sredn_colvo = np.average(dfile9[:,2])
print('Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:',sredn_colvo)

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 28.22


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [38]:
import random
dfile[np.random.choice(len(dfile), size = 10, replace = False)] 

array([[ 74341,     30,      5],
       [272448,     30,     11],
       [101334,     20,      5],
       [343537,     40,     11],
       [ 15247,     30,      5],
       [367695,      4,      3],
       [259702,      5,      7],
       [ 32699,     40,     14],
       [208144,     45,     13],
       [320695,     30,      7]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [39]:
p_1 = np.mean(dfile[:,2])
dfile10 = dfile[dfile[:,2]<p_1]
res_1=len(dfile10[:,2])/len(dfile[:,2])
res_1*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [41]:
ar_cond=(dfile[:,1] <= 20) & (dfile[:,2] <= 5)
ar_simp=dfile[dfile[:,1]<=20]
ar_simp_1=ar_simp[ar_simp[:,2]<=5]
ar_add=np.hstack((dfile, ar_cond[:, np.newaxis]))
ar_add

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [42]:
print(len(ar_simp_1)*100/len(dfile))

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [43]:
dfile14 = np.copy(dfile)
short_recipe = dfile14[dfile[:,1] < 10]
midle_recipe = dfile14[(10 <= dfile[:,1]) & (dfile[:,1] < 20)]
long_recipe = dfile14[dfile[:, 1] >= 20]
min_recipe = min(len(short_recipe), len(midle_recipe), len(long_recipe))
print(min_recipe)
itog_recipes = np.array([short_recipe[:min_recipe], midle_recipe[:min_recipe], long_recipe[:min_recipe]])
itog_recipes

7588


array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]])